// keymap.js

// Mapping of characters to press instructions
const keyInstructions = {
    // Letters
    'a': 'Left pinky finger',
    'A': 'Left pinky finger with Right Shift',
    'b': 'Left index finger',
    'B': 'Left index finger with Right Shift',
    'c': 'Left middle finger',
    'C': 'Left middle finger with Right Shift',
    'd': 'Left index finger',
    'D': 'Left index finger with Right Shift',
    'e': 'Left middle finger',
    'E': 'Left middle finger with Right Shift',
    'f': 'Left index finger',
    'F': 'Left index finger with Right Shift',
    'g': 'Left index finger',
    'G': 'Left index finger with Right Shift',
    'h': 'Right index finger',
    'H': 'Right index finger with Left Shift',
    'i': 'Right middle finger',
    'I': 'Right middle finger with Left Shift',
    'j': 'Right index finger',
    'J': 'Right index finger with Left Shift',
    'k': 'Right middle finger',
    'K': 'Right middle finger with Left Shift',
    'l': 'Right ring finger',
    'L': 'Right ring finger with Left Shift',
    'm': 'Right index finger',
    'M': 'Right index finger with Left Shift',
    'n': 'Right index finger',
    'N': 'Right index finger with Left Shift',
    'o': 'Right ring finger',
    'O': 'Right ring finger with Left Shift',
    'p': 'Right pinky finger',
    'P': 'Right pinky finger with Left Shift',
    'q': 'Left pinky finger',
    'Q': 'Left pinky finger with Right Shift',
    'r': 'Left index finger',
    'R': 'Left index finger with Right Shift',
    's': 'Left ring finger',
    'S': 'Left ring finger with Right Shift',
    't': 'Left index finger',
    'T': 'Left index finger with Right Shift',
    'u': 'Right index finger',
    'U': 'Right index finger with Left Shift',
    'v': 'Left index finger',
    'V': 'Left index finger with Right Shift',
    'w': 'Left ring finger',
    'W': 'Left ring finger with Right Shift',
    'x': 'Left ring finger',
    'X': 'Left ring finger with Right Shift',
    'y': 'Right index finger',
    'Y': 'Right index finger with Left Shift',
    'z': 'Left pinky finger',
    'Z': 'Left pinky finger with Right Shift',

    // Numbers and Symbols
    '1': 'Left pinky finger',
    '!': 'Left pinky finger with Right Shift',
    '2': 'Left ring finger',
    '@': 'Left ring finger with Right Shift',
    '3': 'Left middle finger',
    '#': 'Left middle finger with Right Shift',
    '4': 'Left index finger',
    '$': 'Left index finger with Right Shift',
    '5': 'Left index finger',
    '%': 'Left index finger with Right Shift',
    '6': 'Right index finger',
    '^': 'Right index finger with Left Shift',
    '7': 'Right index finger',
    '&': 'Right index finger with Left Shift',
    '8': 'Right middle finger',
    '*': 'Right middle finger with Left Shift',
    '9': 'Right ring finger',
    '(': 'Right ring finger with Left Shift',
    '0': 'Right pinky finger',
    ')': 'Right pinky finger with Left Shift',

    // Special Characters
    '-': 'Right pinky finger',
    '_': 'Right pinky finger with Left Shift',
    '=': 'Right pinky finger',
    '+': 'Right pinky finger with Left Shift',
    '[': 'Left pinky finger',
    '{': 'Left pinky finger with Right Shift',
    ']': 'Left pinky finger',
    '}': 'Left pinky finger with Right Shift',
    '\\': 'Left pinky finger',
    '|': 'Left pinky finger with Right Shift',
    ';': 'Right pinky finger',
    ':': 'Right pinky finger with Left Shift',
    "'": 'Right pinky finger',
    '"': 'Right pinky finger with Left Shift',
    ',': 'Right middle finger',
    '<': 'Right middle finger with Left Shift',
    '.': 'Right ring finger',
    '>': 'Right ring finger with Left Shift',
    '/': 'Right pinky finger',
    '?': 'Right pinky finger with Left Shift',
    '`': 'Left pinky finger',
    '~': 'Left pinky finger with Right Shift',

    // Spacebar
    ' ': 'Thumb (either hand)',
};

